# Generated by Django 5.2.7 on 2025-11-18 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('website', 'Website'), ('other', 'Other')], default='website', max_length=50)),
                ('url', models.URLField(help_text='Full URL to the social profile or link')),
                ('handle', models.CharField(blank=True, help_text='Optional username/handle', max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_icons/%Y/%m/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='home.partner')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='home.profile')),
            ],
            options={
                'ordering': ['order', '-created_on'],
                'unique_together': {('platform', 'profile', 'partner')},
            },
        ),
    ]
