# Generated by Django 5.2.7 on 2025-11-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carouselslide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='link',
        ),
    ]
