# Generated by Django 5.2.7 on 2025-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='Campaigh',
            field=models.ImageField(blank=True, null=True, upload_to='campaigh'),
        ),
    ]
