# Generated by Django 5.2.7 on 2025-12-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_campaign_campaigh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='Campaigh',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
