# Generated by Django 5.2.7 on 2025-12-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_campaign_campaigh_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkdin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
