# Generated by Django 5.2.7 on 2025-12-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sitesetting_facebook_sitesetting_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkdin',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
