# Generated by Django 5.2.7 on 2025-12-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_sitesetting_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='copyright',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
