# Generated by Django 5.2.7 on 2025-12-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sitesetting_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='nav_color',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='text_color',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
