# Generated by Django 5.2.7 on 2025-12-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_sitesetting_nav_color_sitesetting_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='nav_color',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='text_color',
        ),
    ]
