# Generated by Django 5.2.7 on 2025-12-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_sitesetting_nav_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='nav_color',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
