# Generated by Django 5.2.7 on 2025-12-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_sitesetting_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer', models.CharField(max_length=3000)),
            ],
            options={
                'verbose_name': 'Disclaimer',
                'verbose_name_plural': 'Disclaimer',
            },
        ),
    ]
