# Generated by Django 5.2.7 on 2025-12-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_disclaimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclaimer',
            name='disclaimer',
            field=models.TextField(max_length=3000),
        ),
    ]
