# Generated by Django 5.2.7 on 2025-12-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_disclaimer_disclaimer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagecontent',
            options={'ordering': ['order'], 'verbose_name': 'About Page Content', 'verbose_name_plural': 'About Page Content'},
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
