# Generated by Django 5.2.7 on 2025-12-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_aboutpagecontent_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='sponsorship_level',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='website',
        ),
    ]
