# Generated by Django 5.2.7 on 2025-12-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_sponsorship_level_partner_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/'),
        ),
    ]
