# Generated by Django 5.2.7 on 2025-12-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_partner_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='partners_banner',
            field=models.ImageField(blank=True, null=True, upload_to='partners_banner/'),
        ),
    ]
