# Generated by Django 5.2.7 on 2025-12-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_sitesetting_partners_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='content',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
