# Generated by Django 5.2.7 on 2025-12-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_aboutpagecontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_banner',
            field=models.ImageField(blank=True, null=True, upload_to='about_banner/'),
        ),
    ]
