# Generated by Django 5.2.7 on 2025-12-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_sitesetting_about_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='paymant_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment/'),
        ),
    ]
