# Generated by Django 5.2.7 on 2025-12-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_sitesetting_paymant_qr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='paymant_qr',
            new_name='payment_qr',
        ),
    ]
