# Generated by Django 5.2.7 on 2025-12-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_paymant_qr_sitesetting_payment_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contect_banner',
            field=models.ImageField(blank=True, null=True, upload_to='contect_banner/'),
        ),
    ]
