# Generated by Django 5.2.7 on 2025-12-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_sitesetting_contect_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='googlemap',
            field=models.ImageField(blank=True, null=True, upload_to='contect_banner/'),
        ),
    ]
