# Generated by Django 5.2.7 on 2025-12-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_sitesetting_googlemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='googlemap',
            field=models.TextField(blank=True, null=True),
        ),
    ]
