# Generated by Django 5.2.7 on 2025-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmetric',
            name='icon',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
