# Generated by Django 5.2.7 on 2025-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_impactmetric_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
