# Generated by Django 5.2.7 on 2025-12-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_teammember_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number comes first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leadership Member',
                'verbose_name_plural': 'Leadership Members',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='slug',
        ),
    ]
