# Generated by Django 5.2.7 on 2025-12-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_leadership_remove_teammember_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
